#!/bin/bash

#
# Parse the tail of the data
#

tmp=$(mktemp)

tail /home/embed/tempBT.txt > $tmp

/home/embed/thermobeaconLogger/bin/python /home/embed/thermobeaconLogger/parse_brifit.py $tmp  1 1
rm $tmp


